### ISSUE TITLE
Force to use config

### ISSUE THREAD

**Issue by pirmax** [SocialiteProviders/Manager#103]
I use SocialiteProviders to login with two Twitter apps.

```
use Laravel\Socialite\Facades\Socialite;
use SocialiteProviders\Manager\Config;

return Socialite::with('twitter')->setConfig(new Config(
            $this->key,
            $this->secret,
            $this->callback,
            [
                //
            ]
        ))->redirect();
```

I have this error:

> Configuration for TWITTER_KEY is missing. There is no services entry for twitter

**Comment by faustbrian** [comment]
As I stated multiple times before then this issue has been opened. Please submit a PR with a fix as you are already experiencing this issue and I am left alone with the whole SocialiteProviders project, so I don't exactly have a whole lot of time to maintain this on-top of a full-time job without any PRs.

**Comment by faustbrian** [comment]
@pirmax Try this commit https://github.com/SocialiteProviders/Manager/commit/4cc05ae61f5ca4fbc6dd08b304f915fb35c1199c
