### ISSUE TITLE
incorrect phpdoc type description

### ISSUE THREAD

**Issue by angel-rsa** [SocialiteProviders/Manager#107]
https://github.com/SocialiteProviders/Manager/blob/ac108bce073135a55dfebf28ceaf1459669348e8/src/OAuth2/AbstractProvider.php#L60
$body parameter in "parseAccessToken", "parseRefreshToken" and "parseExpiresIn" methods must be an array (in annotations)

**Comment by faustbrian** [comment]
Feel free to submit a PR.
