### ISSUE TITLE
Trouble trying to extend existing provider.

### ISSUE THREAD

**Issue by websanova** [SocialiteProviders/Manager#108]
I'm having issues trying to use the manager to extend an existing provider.

I'm making this call:

```
$user = Socialite::with('facebook')->stateless()->user();
```

Seems to be picking up the events ok but it keeps throwing me this error:

```
Call to undefined method App\SocialiteProviders\Facebook\Provider::additionalConfigKeys()
```

I tried adding this `additionalConfigKeys` function, but it keeps just throwing more and more errors.

I looked at some of the existing providers provided with `SocialiteProviders` but don't see much there.

Not really sure what I'm doing wrong, just trying to extend an existing one.

**composer.json**

```
"laravel/socialite": "3.0.7",
"socialiteproviders/manager": "3.2.1",
```

**EventServiceProvider**

```
protected $listen = [
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        'App\SocialiteProviders\Facebook\FacebookExtendSocialite@handle',
    ],
];
```

**FacebookExtendSocialite**

```
namespace App\SocialiteProviders\Facebook;

use SocialiteProviders\Manager\SocialiteWasCalled;

class FacebookExtendSocialite
{
    /**
     * Register the provider.
     *
     * @param \SocialiteProviders\Manager\SocialiteWasCalled $socialiteWasCalled
     */
    public function handle(SocialiteWasCalled $socialiteWasCalled)
    {
        $socialiteWasCalled->extendSocialite(
            'facebook', __NAMESPACE__.'\Provider'
        );
    }
}
```

**Provider**

```
namespace App\SocialiteProviders\Facebook;

class Provider extends \Laravel\Socialite\Two\FacebookProvider
{
    public function addUser($service)
    {
        echo 'addFacebookUser';
    }
}
```

**Comment by faustbrian** [comment]
Why would you extend the `Laravel\Socialite\Two\FacebookProvider` if you want to replace it? The whole point is to use the base classes provided by the Manager that provides additional methods that Socialite itself doesn't provide.

If you wish to overwrite a Socialite Provider you will need to completely rebuild it. Take a look at the Twitter Provider for example https://github.com/SocialiteProviders/Providers/tree/master/src/Twitter

**Comment by hari-web** [comment]
@websanova, I was looking the same. But now this is possible in Socialite new version(version 2 ). We just need to follow the steps @websanova  listed above!. Thanks a lot.
