### ISSUE TITLE
Using relative path will not automatically be resolved to a fully qualified URL.

### ISSUE THREAD

**Issue by suabahasa** [SocialiteProviders/Manager#109]
# Issue / Motivation:
Using relative path will not automatically be resolved to a fully qualified URL.

I have try to modify  SocialiteProviders/Manager but I have no idea to pass "SocialiteManager $socialite" to "SocialiteProviders\Manager\Config" class.

## Expected behavior:

the redirect URI should resolved to a fully qualified URL

expected URI: "http://localhost/login/discord/callback"

## Actual behavior:

Actual URI: "/login/discord/callback"

## Steps to reproduce the behavior:
Do normal installation.

next, add credentials to "config/services.php" configuration file

    'discord' => [
        'client_id' => env('DISCORD_APP_ID'),
        'client_secret' => env('DISCORD_SECRET'),
        'redirect' => '/login/discord/callback', 
    ], 

## Proposed solution:

First, open "SocialiteProviders\Manager\SocialiteWasCalled" class.

my temporary solution is by comment "$provider->setConfig($config);" expression on method buildOAuth2Provider and buildOAuth1Provider.

    protected function buildOAuth2Provider(SocialiteManager $socialite, $providerClass, $providerName)
    {
        $this->classExtends($providerClass, \Laravel\Socialite\Two\AbstractProvider::class);

        $config = $this->getConfig($providerClass, $providerName);

        $provider = $socialite->buildProvider($providerClass, $config->get());

        // $provider->setConfig($config); <---- by comment this line

        return $provider;
    }

**Comment by faustbrian** [comment]
Just use an absolute URL as even the official Laravel Socialite docs use an absolute URL. There is no reason to use a relative URL.

**Comment by suabahasa** [comment]
In official Laravel Socialite docs mentioned "If the redirect option contains a relative path, it will automatically be resolved to a fully qualified URL." 

Also on Laravel\Socialite\SocialiteManager@formatConfig, it support to resolve the relative url.
its a good choise to use relative url to minimize configuration task.

please considire it. ty

**Comment by faustbrian** [comment]
Feel free to send a PR with tests for this.

**Comment by sander3** [comment]
This should've been in the docs... If you switch from Laravel Socialite to SocialiteProviders, it's hard to pinpoint the difference in configuration handling.

**Comment by m1guelpf** [comment]
Feel free to PR it
