### ISSUE TITLE
The requested package socialiteprovider/manager could not be found in any version

### ISSUE THREAD

**Issue by Alagunto** [SocialiteProviders/Manager#122]
I cannot install socialiteprovider/manager with composer from my projects (where it surely worked before), what's up?

**Comment by faustbrian** [comment]
Maybe try the correct package name https://github.com/SocialiteProviders/Manager/blob/master/composer.json#L2.

**Comment by Alagunto** [comment]
Soz, my stupid typo came out of nowhere -.-
