### ISSUE TITLE
Dynamic config for stock Socialite providers

### ISSUE THREAD

**Issue by antonkomarev** [SocialiteProviders/Manager#131]
I wanted to change config of Github provider on the fly. Am I right that there is no way to do it without creating my own `GithubProvider` which will replace `Laravel\Socialite\Two\GithubProvider`?

I've found [Twitter, LinkedIn and Gitlab providers here](https://github.com/SocialiteProviders/Providers/tree/master/src) but I don't see Github and Bitbucket in the list. Should I make a PR to add extended versions to the list?

Facebook exists in the list, but not exists as split repository and not registered in packagist: http://packagist.org/packages/socialiteproviders/facebook

**Comment by antonkomarev** [comment]
Added PRs to make stock Socialite drivers configurable.
- GitHub driver: https://github.com/SocialiteProviders/Providers/pull/249
- Bitbucket driver: https://github.com/SocialiteProviders/Providers/pull/249

**Comment by m1guelpf** [comment]
Added Facebook repo to Packagist

**Comment by antonkomarev** [comment]
Thanks for the help @m1guelpf!
