### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by antonkomarev** [SocialiteProviders/Manager#132]
@m1guelpf Is there is an ability to have extra composer package which will include all the Providers together? I just want to have all of them in my application, and don't want to install and update them one by one.

`composer require socialiteproviders/providers` which will clone https://github.com/SocialiteProviders/Providers repository.

Only one provider has nested `src` folder inside of the provider directory, so if its structure will be updated it will be completely satisfy PSR-4 standard.
- OSChina

**Comment by antonkomarev** [comment]
It wouldn't be a breaking change because their namespace wouldn't change, it will be just modified in their local `composer.json` file.

**Comment by m1guelpf** [comment]
Why would you do that?

**Comment by m1guelpf** [comment]
Merged your PR

**Comment by antonkomarev** [comment]
Thanks. I need to provide a list of all supported providers to client, and make him able to choose what to connect without affecting an application. Right now it will be pretty complicated task.

**Comment by m1guelpf** [comment]
You can probably do some Filesystem magic to get a list of directories 🤔

**Comment by antonkomarev** [comment]
But if somebody will add new provider - I will be required to install it manually. I just don't want to have 144+ dependencies in application composer.json file.

**Comment by m1guelpf** [comment]
Any ideas on how to improve this?

**Comment by antonkomarev** [comment]
@m1guelpf leave it as is, not all the developers will need all the bunch of the providers.
But additionally we could add one more `composer.json` in the root folder and register new package `socialiteproviders/providers` which will be targeted to the root. I will make a PR soon.

**Comment by antonkomarev** [comment]
Thank you @m1guelpf, it's working as a charm!

**Comment by m1guelpf** [comment]
Awesome!

**Comment by antonkomarev** [comment]
Bad news... I was wrong. There are 14 providers which namespaces are not satisfy PSR-4 compliance.
Dashes, dots and prefix numbers are illegal characters for the namespaces. So, their namespaces looks a bit different from their directory names.

| Directory | Namespace |
| --------- | --------- |
| src\23andme | TwentyThreeAndMe |
| src\37Signals | ThirtySevenSignals |
| src\500px | FiveHundredPixel |
| src\App.net | AppNet |
| src\Battle.net | Battlenet |
| src\Bit.ly | Bitly |
| src\Google-Plus | Google |
| src\Human-API | HumanApi |
| src\Microsoft-Azure | Azure |
| src\Microsoft-Graph | Graph |
| src\Microsoft-Live | Live |
| src\Microsoft-TeamService | TeamService |
| src\PayPal-Sandbox | PayPalSandbox |
| src\Weixin-Web | WeixinWeb |

**Comment by antonkomarev** [comment]
I understand why this was done with folders with digits, but the worst thing that some of them breaking naming convention:
- `Google-Plus` called `Google` instead of `GooglePlus`
- `Microsoft-Azure` called `Azure` instead of `MicrosoftAzure`
- `Microsoft-Graph` called `Graph` instead of `MicrosoftGraph`
- `Microsoft-Live` called `Live` instead of `MicrosoftLive`
- `Microsoft-TeamService` called `TeamService` instead of `MicrosoftTeamService`

**Comment by antonkomarev** [comment]
I need some more time to find the right solution to make migration to the same naming convention without breaking changes.

*This issue should be transfered to [SocialiteProviders/Providers](https://github.com/SocialiteProviders/Providers) repository. My bad, created it in wrong place.*
