### ISSUE TITLE
ConfigResolver overwriting

### ISSUE THREAD

**Issue by antonkomarev** [SocialiteProviders/Manager#133]
# Issue / Motivation:

I can't store configuration of provider in services config file.
Because of it I'm receiving `MissingConfigException`:

> There is no services entry for github

I've tried to replace `ConfigResolver` with my own implementation.
Added to `App\Providers\AppServiceProvider`:

```php
$this->app->singleton(
    \SocialiteProviders\Manager\Contracts\Helpers\ConfigRetrieverInterface::class,
    \App\CustomConfigRetriever::class
);
```

But no luck, because `ServiceProvider` of the package loading after the `AppServiceProvider` and overwrites my binding.

## Proposed solution:

It looks like I have to disable auto-discovery of `"socialiteproviders/manager"` in composer.json and load service provider manually, and only after that rebind `ConfigResolver`. Is there any other thoughts how this could be solved?

**Comment by m1guelpf** [comment]
Can you store a mock configuration and replace it when redirecting?

**Comment by antonkomarev** [comment]
Yes, but how can I do it if it's automatically tries to resolve config from services?

**Comment by antonkomarev** [comment]
Disabling discovery and registering provider manually has negative side effects. Then `SocialiteWasCalled` event will be fired on every application call, even when it wasn't called.

**Comment by antonkomarev** [comment]
Nice, we've got unreachable statement. And that's exactly what I need. Fill provider with spoofed config to overwrite it later.

https://github.com/SocialiteProviders/Manager/blob/f87057486472e35cf0a208c870f613289806ade1/src/SocialiteWasCalled.php#L150-L165

**Comment by antonkomarev** [comment]
That's hidden not in the trait. It's event which called when Socialite is required. I've found more issues and described them in other threads. Will try to help you out later.

**Comment by antonkomarev** [comment]
Additionally I've found some more issues:

1. There is unused class property:
```php
private $configRetriever;
```

2. `resolve` helper method not found (that's why tests are failing). I don't know why it was used instead of DI to `__construct` method [which was used before](https://github.com/SocialiteProviders/Manager/blob/1de3f3d874392da6f1a4c0bf30d843e9cd903ea7/src/SocialiteWasCalled.php).

**Comment by m1guelpf** [comment]
Awesome, thanks for all your work here!
