### ISSUE TITLE
opt: set credentialsResponseBody before getUserByToken

### ISSUE THREAD

**Issue by sinkcup** [SocialiteProviders/Manager#141]
# Issue / Motivation: 

now can not use credentialsResponseBody in getUserByToken

## Expected behavior:

set credentialsResponseBody before getUserByToken, so can use it

## Actual behavior:

set credentialsResponseBody after getUserByToken

## Steps to reproduce the behavior:

Tencent WeChat Service Account Login break OAuth 2, it return user id in access token API, and can not get user info by this token, so we need use credentialsResponseBody when getUserByToken.

https://github.com/SocialiteProviders/Providers/blob/master/src/Weixin/Provider.php#L80

```
{ 
    "access_token":"ACCESS_TOKEN",
    "expires_in":7200,
    "refresh_token":"REFRESH_TOKEN",
    "openid":"OPENID",
    "scope":"SCOPE" 
}
```

## Proposed solution:

move line 46 to line 41.

https://github.com/SocialiteProviders/Manager/blob/master/src/OAuth2/AbstractProvider.php#L46

**Comment by sinkcup** [comment]
there are 4 commits in this three months, maybe could release a new version. @m1guelpf 

![image](https://user-images.githubusercontent.com/4971414/56643699-b181e980-66ac-11e9-84fc-9c37b4f77088.png)

**Comment by m1guelpf** [comment]
Done!

**Comment by keesh7663** [comment]
As an FYI, this completely breaks Discord Socialite login
