### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by dpsarrou** [SocialiteProviders/Manager#146]
# Issue / Motivation:
I would like to update my project to laravel 6 and this package's dependency to `illuminate/support` up to `~5.8.0` is preventing me.

## Expected behavior:
`composer update` should allow me to update the project

## Actual behavior:
Composer errors complaining about unsupported dependency.

## Steps to reproduce the behavior:
Given `composer.json` defines a dependency of `"laravel/framework": "^6.0"`, running `composer prohibits laravel/framework` shows:
```
socialiteproviders/manager          v3.3.7        requires  illuminate/support (~5.4|~5.7.0|~5.8.0)
```

## Proposed solution:
Add support for `"illuminate/support":"~5.4|~5.7.0|~5.8.0|^6.0"` similar to how [laravel/socialite](https://github.com/laravel/socialite/blob/4.0/composer.json#L22) is supporting it.

**Comment by m1guelpf** [comment]
Just tagged a new release

**Comment by Francismori7** [comment]
> Just tagged a new release

The new release does not actually work with 6.0 though. See #147

**Comment by m1guelpf** [comment]
@Francismori7 I also encountered this yesterday after tagging the release, but couldn't find the issue. My workaround was to add this to the boot method of my EventServiceProvider:

```php
event(app(SocialiteWasCalled::class));
```

Glad to accept any PR that fixes this

**Comment by m1guelpf** [comment]
@Francismori7 tagged a new release
