### ISSUE TITLE
Register provider listeners not being called after updating to Laravel 6.0

### ISSUE THREAD

**Issue by ethanransdellrarebird** [SocialiteProviders/Manager#147]
# Issue / Motivation:
Register provider listeners not being called

## Expected behavior:
`Socialite::driver('azure')->redirect();` should redirect to the provider's login page

## Actual behavior:
`InvalidArgumentException with message 'Driver [azure] not supported.'`

## Steps to reproduce the behavior:
- Create a new Laravel project with version `5.8.*`
- Install `socialiteproviders/microsoft-azure` in Composer, `app.php`, and `EventServiceProvider.php`
- Change `laravel/framework` dependency to `^6.0` and run `composer update`

## Proposed solution:
I've been troubleshooting and see that in this case, the `AzureExtendSocialite` listener is not being triggered. I was able to dispatch the event manually in `tinker` and get a die dump from `AzureExtendSocialite` but still could not get a redirect.

**Comment by Clayboy** [comment]
I have the same issue with `InstagramExtendSocialite` listener.

Debugging with Laravel Telescope, `SocialiteWasCalled` event is dispatched but no listener are triggered (even if found in `php artisan event:list`).

Maybe an execution order issue.

**Comment by Francismori7** [comment]
Same thing here.

**Comment by ethanransdellrarebird** [comment]
Found that firing the SocialiteWasCalled event is not being added to the app's booted callbacks. Working on a PR.

**Comment by m1guelpf** [comment]
Tagged a new release
