### ISSUE TITLE
Facebook sdk v4.0 and twitter oauth2

### ISSUE THREAD

**Issue by lukadriel7** [SocialiteProviders/Manager#151]
# Issue / Motivation:
Hello, I have started started using laravel/socialite with the socialite providers. I was able to connect to google without much problem but I am currently unable to use the twitter and facebook providers. I am using a single page application so I call the stateless method on the redirect method.
## Expected behavior:
Being able to connect to twitter and facebook
## Actual behavior:
The facebook page is blank and crash, the twitter redirect return a 500 error about Session store not stored on request
## Steps to reproduce the behavior:

- Create new laravel application
- Install laravel/socialite and socialiteproviders/facebook and twitter
- Configure socialite and socialite providers following tutorial 
- Configure login route on api route and callback route on web 
- Use client to login by calling the api login route

## Proposed solution:
I may be wrong but:
- The facebook provider seems to be using the v3 of the facebook api which seems to be deprecated. It may be the problem. 
- The twitter provider on the other hand seems to use oauth 1 instead of oauth2 which causes the stateless error. Twitter now having oauth2, the solution could be to implement it.

**Comment by lukadriel7** [comment]
The facebook one works now, somehow. I guess it was a problem on my side. The twitter one still doesn't.

**Comment by andreas83** [comment]
same issue here with twitter, there is a related PR #157 
please review and merge.
