### ISSUE TITLE
Release >= 3.3.6. breaks Lumen 5.7 application

### ISSUE THREAD

**Issue by ansisblodnieks** [SocialiteProviders/Manager#152]
# Issue / Motivation:

Commit `b634a08aef6c55b7c4575a78a1da3d5cc978bc1b` (release 3.3.6.) breaks application because of non-existent method `booted`  with Lumen 5.7.*

## Expected behavior:

Compatible with Lumen, working app.

## Actual behavior:

Not compatible with Lumen, non-working app.

## Steps to reproduce the behavior:

Install `socialiteproviders/manager` <= 3.3.6., the application is working, with >= 3.3.6. the application is not working.

## Proposed solution:

Should have been released not with minor version but with 3.4. Proposing checking if the method exists if there is no other way.

**Comment by ansisblodnieks** [comment]
Closing issue, needs more testing

**Comment by ansisblodnieks** [comment]
The `booted()` method doesn't exist in `Laravel\Lumen\Application` class.

**Comment by ansisblodnieks** [comment]
Related article - https://laracasts.com/discuss/channels/lumen/call-to-undefined-method-laravellumenapplicationbooted

**Comment by m1guelpf** [comment]
Feel free to PR a fix

**Comment by jtaylor69** [comment]
Just opened a PR as we ran into the same issue.
Does a check to see if you are using Lumen or Laravel and changes the logic to suit whichever you use.

**Comment by jtaylor69** [comment]
It's been a while since I've done a PR so was a little rusty the first time.
Sorted it out into a separate branch and checks have now passed 👍 
Now in PR #154
