### ISSUE TITLE
League/OAuth1 function signature updated

### ISSUE THREAD

**Issue by tobytwigger** [SocialiteProviders/Manager#172]
# Issue / Motivation:
The ```league/oauth1-server``` package, required by ```laravel/socialite``` have decided to update the function signature for ```League\OAuth1\Client\Server\Server::getTokenCredentials``` in the new release, v1.8.0.

Release: https://github.com/thephpleague/oauth1-client/releases/tag/v1.8.0
Change: https://github.com/thephpleague/oauth1-client/compare/1.7.0...v1.8.0
Introduced in commit: https://github.com/thephpleague/oauth1-client/commit/8915bee22d5fee217e052b4faaaf3b076c09cc07

## Expected behavior:

When this package is installed to a Laravel codebase (via ```socialiteproviders/providers```), it installs properly.

## Actual behavior:

An error is thrown due to a mismatch of signatures. Since this package extends the ```League\OAuth1\Client\Server\Server``` class and overrides the ```getTokenCredentials``` method, there is a signature mismatch.

`
Declaration of SocialiteProviders\Manager\OAuth1\Server::getTokenCredentials(League\OAuth1\Client\Credentials\TemporaryCredentials $temporaryCredentials, $temporaryIdentifier, $verifier) must be compatible with League\OAuth1\Client\Server\Server::getTokenCredentials(League\OAuth1\Client\Credentials\TemporaryCredentials $temporaryCredentials, string $temporaryIdentifier, string $verifier): League\OAuth1\Client\Credentials\TokenCredentials
`

## Steps to reproduce the behavior:

Run ```composer install socialiteproviders/providers``` into a laravel app. Set up a provider that uses socialite, e.g. Trello. You may also need to run ```php artisan package:discover --ansi``` to trigger the error, though this is normally done through composer.

My event service provider: 
```
protected $listen = [
        SocialiteWasCalled::class => [
            TrelloExtendSocialite::class,
        ]
];
```

## Proposed solution:

It's harder than just updating the signature for the error above. I've done this, but they also now require a ```League\OAuth1\Client\Server\User``` instance to be returned from the ```userDetails``` function. Most socialite providers using OAuth1 obviously return a ```SocialiteProviders\Manager\OAuth1\User``` instance, which itself doesn't extend the league user. 

I'd suggest we fix the signature mismatch referenced in this issue, as well as any signatures in the Providers repository. I'll also open an issue on Laravel/Socialite to see if it'll cause problems for their OAuth1 user to extend the League OAuth1 user if others agree?

As a temporary fix, fixing the version of league in a Laravel composer.json file will solve the issue: ```"league/oauth1-client": "~1.7.0"```

**Comment by atymic** [comment]
Maybe we should create an issue over there? Not sure if the package uses semver?

**Comment by tobytwigger** [comment]
They say they do in their contributing guide, but I don't know what they count as their public API. Issue opened here: [https://github.com/thephpleague/oauth1-client/issues/118](https://github.com/thephpleague/oauth1-client/issues/118)

**Comment by tobytwigger** [comment]
They're going to roll back the changes and release them in the next major release, and an issue has also been opened in socialite r.e. support for v2 so hopefully that'll support the new version. May be worth keeping an eye on as there probably will be breaking changes on their way though
