### ISSUE TITLE
provider for Yahoo

### ISSUE THREAD

**Issue by madagon** [SocialiteProviders/Manager#21]
hello guys,
can i ask you please to make a provider for Yahoo? it's easy for you but takes a lot from me.

willing hands,
Mohsen

**Comment by DraperStudio** [comment]
You can use the Generators which you can find at https://github.com/SocialiteProviders/Generators to make the process easier, otherwise I might take a look during the weekend.

**Comment by madagon** [comment]
i like the "otherwise" :accept: 
thank you :smile:

**Comment by DraperStudio** [comment]
Won't be able to make the Provider since I don't have a Yahoo account and I can only create one by using my phone number.

**Comment by madagon** [comment]
i've created the account for you.
please check the link immediately and you can open the link only once. so keep the info somewhere on paper.
https://onetimesecret.com/secret/b6n6etd6q3ez68lcz1ewsr83rpjonr0

**Comment by DraperStudio** [comment]
A Yahoo Provider is now available at https://github.com/SocialiteProviders/Yahoo

**Comment by madagon** [comment]
"unknown name", thanks for the work!
could you successfully receive the callback?
i get this message after logging:

"Uh oh
Looks like something went wrong.
Please try again later."

tried different configuration on my yahoo application but no chance.

**Comment by DraperStudio** [comment]
I always perform a test login before I push the providers, so yeah I have received the callback.

Make sure you enable *Profiles (Social Directory) > Read Public* when you create the application.

**Comment by madagon** [comment]
like it's a security exception from yahoo since they don't allow callbacks to localhost.
you've probably tested on a valid domain.

anyway, if you tested on the cloud and it's ok so i guess i can get it work later when i go live.

thanks again for your attention.
gotta get you a beer :beers:

**Comment by DraperStudio** [comment]
I tested it local with Homestead, so you should be good to go both local and in production.
