### ISSUE TITLE
SocialiteWasCalled event constantly firing

### ISSUE THREAD

**Issue by smcgovern** [SocialiteProviders/Manager#214]
# Issue / Motivation:
Recently installed SocialiteProvidersManager in order to get Socialite Discord to work.

## Expected behavior:
SocialiteWasCalled event to only be triggering when a user is logging in? The plugin is working and I am able to login successful through Discord, but I was wondering why this event constantly is triggering.

## Actual behavior:
I see SocialiteWasCalled happening via telescope every few minutes, even if no requests are going to the site.

<img width="940" alt="Screen Shot 2023-01-12 at 11 46 55 PM" src="https://user-images.githubusercontent.com/1742653/212239915-2fff43a8-68fb-42f1-875d-e4481692fb08.png">

Is this normal behavior? Or do I have something setup improperly? What is the reason this happens if it is normal?

Thanks!

**Comment by cyrodjohn** [comment]
@smcgovern Did you figure this out? Is it normal?

**Comment by jtomek** [comment]
It's happening to me as well.

**Comment by lrljoe** [comment]
It'll happen every time the app boots as it runs it in the service provider.

```
class SocialiteWasCalled
```
