### ISSUE TITLE
[Proposal] Own AbstractProviders with Custom Configuration

### ISSUE THREAD

**Issue by DraperStudio** [SocialiteProviders/Manager#26]
So I quickly put something together which makes it possible to have a fluent interface for the config which at the moment is somewhat clunky in my opinion - https://github.com/SocialiteProviders/StackExchange/issues/2#issuecomment-186761408

These changes would require the following changes to all Providers:

- Provider.php has to extend `SocialiteProviders\Manager\OAuth1\AbstractProvider` instead of the `Laravel\Socialite\One\AbstractProvider`
- Provider.php has to extend `SocialiteProviders\Manager\OAuth2\AbstractProvider` instead of the `Laravel\Socialite\Two\AbstractProvider`

Additionally we probably also should introduce our own `User` classes for both OAuth1 and OAuth2 to gain finer control over what is happening and the response data, which you already did for OAuth2.

-----

**OAuth2/AbstractProvider.php**
```php
<?php
namespace SocialiteProviders\Manager\OAuth2;

use GuzzleHttp\ClientInterface;
use Laravel\Socialite\Two\InvalidStateException;
use SocialiteProviders\Manager\SocialiteWasCalled;

abstract class AbstractProvider extends \Laravel\Socialite\Two\AbstractProvider
{
    // all the code of the current AbstractProvider in the OAuth2 folder...

    public function config(array $additionalConfig) {
        $identifier = static::PROVIDER_IDENTIFIER;

        $this->config = array_merge([
            'client_id' => env("{$identifier}_KEY"),
            'client_secret' => env("{$identifier}_SECRET"),
            'redirect' => env("{$identifier}_REDIRECT_URI"),
        ], $additionalConfig);

        return $this;
    }

    protected function getFromConfig($key)
    {
        $identifier = strtolower(static::PROVIDER_IDENTIFIER);

        return app()['config']["services.{$identifier}"][$key];
    }
}
```

**StackExchange/Provider.php**
```php
<?php

namespace SocialiteProviders\StackExchange;

use SocialiteProviders\Manager\OAuth2\AbstractProvider;
use SocialiteProviders\Manager\OAuth2\User;
use Laravel\Socialite\Two\ProviderInterface;

/**
 * https://api.stackexchange.com/docs/authentication
 * Class Provider.
 */
class Provider extends AbstractProvider implements ProviderInterface
{
    const PROVIDER_IDENTIFIER = 'STACKEXCHANGE';

    // all the code we have in the Provider.php file of each package at the moment...
}
```

**routes.php**
```php
Route::group(['middleware' => ['web']], function () {
    \Route::get('/', function() {
        return \Socialite::with('stackexchange')->config([
            'key' => 'yourkeyfortheservice', 'site' => 'stackoverflow'
        ])->redirect();
    });

    \Route::get('/callback', function () {
        $user = \Socialite::with('stackexchange')->user();

        dd($user);
    });
});
```

-----

If this seems like it goes into the right direction I will finish it up.

**Comment by DraperStudio** [comment]
Another thing that came to my mind for easier configuration would be that we automatically load the config by parsing the .env file.

**.env**
```php
STACKEXCHANGE_CLIENT_ID=yourkeyfortheservice
STACKEXCHANGE_CLIENT_SECRET=yoursecretfortheservice
STACKEXCHANGE_REDIRECT_URI=https://homestead.app/callback
STACKEXCHANGE_SITE=stackoverflow
```

Now we would check which variables start with the `PROVIDER_IDENTIFIER ` and build an array like this for the config. For the array keys we would just need to replace the `PROVIDER_IDENTIFIER` and cast the string to lowercase

```php
$config = [
    'client_id' => 'yourkeyfortheservice',
    'client_secret' => 'yoursecretfortheservice',
    'redirect_uri' => 'https://homestead.app/callback',
    'site' => 'stackoverflow',
];
```

**Comment by DraperStudio** [comment]
I have updated all Providers to extend our own AbstractProviders and I will add support for `$user->accessTokenResponseBody` to the OAuth1 Provider soon.

So once we finished this here up I can quickly push an update for all Providers.

**Comment by AndyWendt** [comment]
Just saw this :)  I will take a look at this in the next couple of days and give it some good thought.  This looks like there are some good ideas here :)

**Comment by DraperStudio** [comment]
At the moment the OAuth1 files look like this. When you look at the `Server.php` you will see what I mean by those empty methods.

I don't know if there is a better way to add **accessTokenResponseBody** to the OAuth1 user because the `getTokenCredentials`-method was the only spot I found where I could snatch in and get the response body.

**Twitter/Provider.php**
```php
<?php

namespace SocialiteProviders\Twitter;

use League\OAuth1\Client\Credentials\CredentialsException;
use SocialiteProviders\Manager\OAuth1\User;

class Provider extends TwitterAbstractProvider
{
    /**
     * Unique Provider Identifier.
     */
    const PROVIDER_IDENTIFIER = 'TWITTER';

    /**
     * {@inheritdoc}
     */
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user['extra'])->map(
            [
                'id' => $user['id'],
                'nickname' => $user['nickname'],
                'name' => $user['name'],
                'email' => $user['email'],
                'avatar' => $user['avatar'],
            ]
        );
    }
}
```

**Manager/OAuth1/AbstractProvider.php**
```php
<?php

namespace SocialiteProviders\Manager\OAuth1;

use GuzzleHttp\ClientInterface;
use Laravel\Socialite\One\InvalidStateException;
use SocialiteProviders\Manager\ConfigTrait;
use SocialiteProviders\Manager\SocialiteWasCalled;

abstract class AbstractProvider extends \Laravel\Socialite\One\AbstractProvider
{
    use ConfigTrait;

    protected $credentialsResponseBody;

    public static function serviceContainerKey($providerName)
    {
        return SocialiteWasCalled::SERVICE_CONTAINER_PREFIX.$providerName;
    }

    public function user()
    {
        if (!$this->hasNecessaryVerifier()) {
            throw new \InvalidArgumentException('Invalid request. Missing OAuth verifier.');
        }

        $token = $this->getToken();
        $tokenCredentials = $token['tokenCredentials'];

        $user = $this->mapUserToObject((array) $this->server->getUserDetails($tokenCredentials));
        $user->setToken($tokenCredentials->getIdentifier(), $tokenCredentials->getSecret());

        if ($user instanceof User) {
            parse_str($token['credentialsResponseBody'], $credentialsResponseBody);

            if (!$credentialsResponseBody || !is_array($credentialsResponseBody)) {
                throw new CredentialsException('Unable to parse token credentials response.');
            }

            $user->setAccessTokenResponseBody($credentialsResponseBody);
        }

        return $user;
    }

    protected function getToken()
    {
        $temp = $this->request->getSession()->get('oauth.temp');

        return $this->server->getTokenCredentials(
            $temp, $this->request->get('oauth_token'), $this->request->get('oauth_verifier')
        );
    }
}
```

**Manager/OAuth1/Server.php**
```php
<?php

namespace SocialiteProviders\Manager\OAuth1;

use GuzzleHttp\Exception\BadResponseException;
use League\OAuth1\Client\Credentials\TemporaryCredentials;
use League\OAuth1\Client\Credentials\TokenCredentials;

class Server extends \League\OAuth1\Client\Server\Server
{
    public function getTokenCredentials(TemporaryCredentials $temporaryCredentials, $temporaryIdentifier, $verifier)
    {
        if ($temporaryIdentifier !== $temporaryCredentials->getIdentifier()) {
            throw new \InvalidArgumentException(
                'Temporary identifier passed back by server does not match that of stored temporary credentials.
                Potential man-in-the-middle.'
            );
        }

        $uri = $this->urlTokenCredentials();
        $bodyParameters = array('oauth_verifier' => $verifier);

        $client = $this->createHttpClient();

        $headers = $this->getHeaders($temporaryCredentials, 'POST', $uri, $bodyParameters);

        try {
            $response = $client->post($uri, $headers, $bodyParameters)->send();
        } catch (BadResponseException $e) {
            return $this->handleTokenCredentialsBadResponse($e);
        }

        return [
            'tokenCredentials' => $this->createTokenCredentials($response->getBody()),
            'credentialsResponseBody' => $response->getBody()
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function urlTemporaryCredentials()
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function urlAuthorization()
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function urlTokenCredentials()
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function urlUserDetails()
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function userDetails($data, TokenCredentials $tokenCredentials)
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function userUid($data, TokenCredentials $tokenCredentials)
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function userEmail($data, TokenCredentials $tokenCredentials)
    {
        //
    }

    /**
     * {@inheritdoc}
     */
    public function userScreenName($data, TokenCredentials $tokenCredentials)
    {
        //
    }
}
```

**Comment by DraperStudio** [comment]
@AndyWendt Please take a look at this soon, we have a few Providers which could make good use of this and I want to have this in before I start adding tests to all Providers since it will require some changes.

**Comment by AndyWendt** [comment]
I will take a look at it soon.  I have a PHP User Group meeting that I need to prepare for tomorrow but after that I should be good.

**Comment by DraperStudio** [comment]
@AndyWendt Gonna close this soon if no progress is made and might add it as an extra/optional package.

**Comment by AndyWendt** [comment]
Ok, I will see what I can do here shortly

**Comment by AndyWendt** [comment]
@DraperStudio working on this today

**Comment by AndyWendt** [comment]
@DraperStudio you suggested

> automatically load the config by parsing the .env file.

What if someone wanted a different config per endpoint (as in [Stackexchange](https://github.com/SocialiteProviders/StackExchange/issues/2#issuecomment-186761408))? What if we added an option to parse the config from the .env using a modifier on the facade class?

For example: 

```php
// custom config
\Socialite::with('stackexchange')->config($yourCustomConfig)->redirect();

// config from env
\Socialite::with('stackexchange')->configFromEnv()->redirect();
```

**Comment by DraperStudio** [comment]
I agree that for different configurations per endpoint people should use the `config` method and I like the idea of the `configFromEnv` method.

Should we maybe have the `configFromEnv` method called by default in the background? Meaning people would only need to enter their details in the `.env` file and no longer in both the `.env` and `services.php`

**Comment by AndyWendt** [comment]
It does seem unnecessary to have things in the services array, especially when we already know what the keys are going to be.  Can you think of any reasons why it would be bad to not use the services array?

It seems like it is an extra step.  We could throw an exception if the configuration wasn't found.   Our setup is already somewhat complex, it seems, for some people.

I guess since it auto retrieves from the services array, why not from the .env?

**Comment by AndyWendt** [comment]
I added a waffle board for issues here: https://waffle.io/SocialiteProviders/Manager

**Comment by AndyWendt** [comment]
I'll probably, if it is alright with you, push this out as a 2.0 release once we get things stabilized.

**Comment by DraperStudio** [comment]
I never found the need of entering the details both in the `.env` and `services.php` to complex but the `services.php` seems somewhat redundant because we know the keys for everything since it is always `PROVIDER_SOMEKEY` so I am all for dropping the `services.php` config and automatically loading the config from `.env`.

For missing configurations we probably could do it as simple as that.

```php
public function config(array $additionalConfig)
{
    $this->config = array_merge([
        'client_id' => $this->getFromEnv("KEY"),
        'client_secret' => $this->getFromEnv("SECRET"),
        'redirect' => $this->getFromEnv("REDIRECT_URI"),
    ], $additionalConfig);

    return $this;
}

private function getFromEnv($item)
{
    $identifier = static::PROVIDER_IDENTIFIER;

    $item = env("{$identifier}_{$item}");

    if(empty($item)) {
        throw new MissingEnvConfig("Configuration for $key is missing.");
    }
    
    return $item;
}
```

**Comment by DraperStudio** [comment]
Yeah, releasing a 2.0 would probably be the best. I will update all providers to use the new version once the Manager 2.0 is stable.

**Comment by AndyWendt** [comment]
Probably should remain compliant with the Liskov Substitution Principle and allow the standard Socialite way to work as well.  It looks like I am going to have to extend the SocialiteManager class with our own.

**Comment by DraperStudio** [comment]
Guess we have to keep it then, just don't like to keep such redundant steps in usually.

Do you just need to rebind the Manager in the IoC?

**Comment by AndyWendt** [comment]
I do just need to rebind the manager in the IoC.  We are already registering a service provider so it should work just fine.  We might check first in the services array and then in the .env, or maybe the other way around?

**Comment by DraperStudio** [comment]
One thing that came to my mind right now. Can the `services.php` be cached like the `routes.php` for example? This would might be a reason to use the `services.php`.

**Comment by DraperStudio** [comment]
If the `services.php` can't be cached I would say we should first check the `.env` for configuration.

**Comment by AndyWendt** [comment]
Hmmm... good question.  I don't know but probably.  We'll have to look that up

**Comment by AndyWendt** [comment]
We could also build our own cache

**Comment by DraperStudio** [comment]
I think some kind of cache would be really nice to prevent the constant reading of either the service or env.

**Comment by AndyWendt** [comment]
If we pull things directly out of the env supposedly it will be compliant with Lumen then: http://stackoverflow.com/questions/33135470/laravel-socialite-on-lumen-credentials-are-not-sent-along

**Comment by AndyWendt** [comment]
Lumen uses the same container as Laravel: https://lumen.laravel.com/docs/5.2/container 

So we could put together a cache or just read the env.  Maybe we should start with reading the env and then create a cache if we need it!??!?!?!!?

**Comment by DraperStudio** [comment]
Just reading the env should be fine for now since adding the cache later on won't be BC.

**Comment by AndyWendt** [comment]
Do you mind if I set up a slack channel for us?

**Comment by DraperStudio** [comment]
Joined the Slack channel, will be online tomorrow.

Should we maybe add the cache as an optional package instead of integrating it into the manager?

**Comment by AndyWendt** [comment]
That might be a good option. We'll have to think about it.
