### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by morrislaptop** [SocialiteProviders/Manager#27]

**Comment by DraperStudio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this?

**Comment by AndyWendt** [comment]
http://stackoverflow.com/questions/33135470/laravel-socialite-on-lumen-credentials-are-not-sent-along.  There are some differences that we will have to think about since I believe `Laravel Socialite` is intended for Laravel lol.  But it is doable I believe.

**Comment by DraperStudio** [comment]
@AndyWendt Would a LumenServiceProvider.php be sufficient that had the register-method with the `$this->app->configure('services')` call or should we just add a little text about how to setup Lumen with SocialiteProviders?

**Comment by AndyWendt** [comment]
:+1:
