### ISSUE TITLE
Duplicate method getAccessToken in Manager/src/OAuth2/AbstractProvider.php

### ISSUE THREAD

**Issue by heydavid713** [SocialiteProviders/Manager#49]
# Issue / Motivation:
PHP error when trying to do composer update.

## Expected behavior: 
To not have duplicate methods.

## Actual behavior: 
PHP error.

## Steps to reproduce the behavior:
composer update, or anything at all after the package is updated.

## Proposed solution: 
Remove method in line 89 as following the comments above, it should be deprecated.

**Comment by DraperStudio** [comment]
Removed release `v2.1.3` so try `composer update` or delete your `vendor` directory and run `composer install`.
