### ISSUE TITLE
redeclare getAccessToken()

### ISSUE THREAD

**Issue by wabucewicz** [SocialiteProviders/Manager#50]
After update to version socialiteproviders/manager (v2.1.3) I get error:

[Symfony\Component\Debug\Exception\FatalErrorException]                                
Cannot redeclare SocialiteProviders\Manager\OAuth2\AbstractProvider::getAccessToken()

**Comment by DraperStudio** [comment]
Removed release `v2.1.3` so try `composer update` or delete your `vendor` directory and run `composer install`.
