### ISSUE TITLE
Readme update - IDENTIFIER constant in provider class

### ISSUE THREAD

**Issue by gibex** [SocialiteProviders/Manager#58]
Last version of Manager it require a Provider::IDENTIFIER constant, but I can’t find any reference in docs. What is it’s role?

According to tests/ it’s looking for IDENTIFIER_* variables in env. 

Thank you

**Comment by DraperStudio** [comment]
`IDENTIFIER` is a variable in Provider classes which gets replaced by `TWITTER` for example.
