### ISSUE TITLE
How to use default socialite providers with this package?

### ISSUE THREAD

**Issue by chimit** [SocialiteProviders/Manager#66]
Hi, @AndyWendt! I've seen your [comment](http://stackoverflow.com/a/37421713/740137) on StackOverflow, where you wrote, that SocialiteProviders solves the problem with `config/services.php` in Lumen out of the box.

**SocialiteProviders** packages can read `.env` file directly, and it's awesome, but there are no Facebook, Google, and other default Socialite providers in this package. So how to make them read `.env` variables too?

**Comment by faustbrian** [comment]
We would need to reimplement those Providers since they use Laravel Socialite directly and not our Manager Package thus it is not possible with the default Laravel Providers.
