### ISSUE TITLE
Session data I provide when testing gets ignored by Vkontakte provider

### ISSUE THREAD

**Issue by x-yuri** [SocialiteProviders/Manager#70]
The issue is apparently not with this particular provider. If we inspect what happens when Facebook driver/provider is created, we can see that it's created, say, on demand. When `Socialite::driver('facebook')` is called in controller, it [follows][fb1] [this][fb2] [path][fb3].

With SocialiteProviders though, it [takes][sp1] the [other][sp2] [route][sp3]. With provider being created [in advance][sp4].

As a result, when I test routes that makes use of Vkontakte provider

```php
          return $this->withSession([
              'state' => '...',
          ])->get('/auth/vkontakte/callback?' . http_build_query([
              'state' => '...',
          ]));
```

provided state gets ignored. Workarounds are welcome.

P.S. I'm going to investigate it a little more...

[fb1]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Support/Manager.php#L87
[fb2]: https://github.com/laravel/socialite/blob/v2.0.20/src/SocialiteManager.php#L48-L50
[fb3]: https://github.com/laravel/socialite/blob/v2.0.20/src/SocialiteManager.php#L90-L93
[sp1]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Support/Manager.php#L85
[sp2]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Support/Manager.php#L101
[sp3]: https://github.com/SocialiteProviders/Manager/blob/v2.1.9/src/SocialiteWasCalled.php#L52-L56
[sp4]: https://github.com/SocialiteProviders/Manager/blob/v2.1.9/src/SocialiteWasCalled.php#L48

**Comment by x-yuri** [comment]
[This way][1] it totally works. What do you say?

[1]: https://github.com/SocialiteProviders/Manager/compare/master...x-yuri:testing-boot

**Comment by faustbrian** [comment]
You are welcome to send a PR for this.
