### ISSUE TITLE
set() -> put()

### ISSUE THREAD

**Issue by slava-vishnyakov** [SocialiteProviders/Manager#73]
Laravel 5.4 removes `set()` method on session:

> All calls to the `->set()` method should be changed to `->put()`. Typically, Laravel applications would never call the set method since it has never been documented within the Laravel documentation. However, it is included here out of caution.

https://laravel.com/docs/5.4/upgrade

So, this line no longer works in 5.4:

https://github.com/SocialiteProviders/Manager/blob/63932b273c6b8a9a88d1a3e90d0353cb0cd024fc/src/OAuth1/AbstractProvider.php#L74

`$this->request->session()->set('oauth_temp', serialize($temp));`

It needs to be `put('oauth_temp', serialize($temp))`

**Comment by faustbrian** [comment]
Then please submit a pull request if you already have the solution.

**Comment by slava-vishnyakov** [comment]
Yes, I'm building a PR, but not quite sure it works, I'll let you know.

Thank you for your work!

**Comment by slava-vishnyakov** [comment]
Yes, the fix works. Also will send a PR to fix Jira integration
