### ISSUE TITLE
Gitlab - Laravel 5.4 - Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist

### ISSUE THREAD

**Issue by lukepolo** [SocialiteProviders/Manager#77]
# Issue / Motivation:
`Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist`

## Expected behavior:
Should be able to use 

`GitLabExtendSocialite::class.'@handle',` in my `$listen` array 

## Actual behavior:
 gives error 

`Class SocialiteProviders\GitLab\GitLabExtendSocialite does not exist`

## Steps to reproduce the behavior:
Follow guide, 

make sure you have in app providers : 

`SocialiteProviders\Manager\ServiceProvider::class,`

**Comment by faustbrian** [comment]
https://github.com/SocialiteProviders/Providers/commit/cc9ed52bf1b8ede2810a8006cafdeda8429d24b3
