### ISSUE TITLE
$scopeSeparator causing issues with some providers

### ISSUE THREAD

**Issue by Bozzified** [SocialiteProviders/Manager#82]
# Issue / Motivation:
need an option to change scope operator type instead of default comma to whatever is needed.

## Expected behavior:
scopeSeparator should work for all providers however for some due to different providers requirements for scope format there should be an ability to change it to whatever is needed

## Actual behavior:
Using Dribbble provider causes an error when setting scope because it requires a space between defined scopes. So right now if I add additional scopes to the array of Socialite->scopes they will be separated by comma. Dribbble does not accept that format but will return unauthorized error due to bad scopes. 

Example of regular scopes that work:  scopes['publish', 'write'] -> Socalite returns scope as scopes=publish,write

However in this case, Dribbble requires it to look like this:
scopes['publish', 'write'] -> Socialite should return scopes=publish write.

Notice the space instead of comma. 

## Proposed solution:
Make it easy to change the $scopeSeparator to whatever is needed.

**Comment by faustbrian** [comment]
Send a PR to https://github.com/SocialiteProviders/Providers
