### ISSUE TITLE
Unable to register ServiceProvider

### ISSUE THREAD

**Issue by jrseliga** [SocialiteProviders/Manager#84]
# Issue / Motivation:
SocialiteManager fails to find appropriate driver if the `SocialiteProviders\Manager\ServiceProvider` is registered to the application via another `ServiceProvider` like `App\Providers\AppServiceProvider`

## Expected behavior:

Registering `SocialiteProviders\Manager\ServiceProvider` via `App\Providers\AppServiceProvider`

```php
public function register()
{
	app()->register(\SocialiteProviders\Manager\ServiceProvider::class);
}
```

should be functionally equivalent to adding `SocialiteProviders\Manager\ServiceProvider` in `config\app.php`:
```php
/*
* Package Service Providers...
*/
SocialiteProviders\Manager\ServiceProvider::class,
```
#### Per Laravel DocBlock
`app()->register()` calls `register` on `Illuminate\Foundation\Application` which states:

```php
/**
* Register a service provider with the application.
*
* @param  \Illuminate\Support\ServiceProvider|string  $provider
* @param  array  $options
* @param  bool   $force
* @return \Illuminate\Support\ServiceProvider
*/
```

## Actual behavior:
SocialiteManager fails to find appropriate driver:

```
InvalidArgumentException in Manager.php line 90: Driver [azure] not supported.
```

## Steps to reproduce the behavior:
1. Install a clean Laravel App (probably want to `php artisan make:auth` to expedite the process)
2. Follow the instructions to setup a SocialiteProviders provider of your choosing per documentation.
3. Modify login controller to support configured SocialiteProvider
4. Confirm working
5. Remove `SocialiteProviders\Manager\ServiceProvider::class` from `config/app.php`
6. In `App\Providers\AppServiceProvider` update the `register` method:

```php
public function register()
{
	app()->register(\SocialiteProviders\Manager\ServiceProvider::class);
}
```
7. Attempt to login again with SocialiteProvider

## Proposed solution:
Unknown

**Comment by a-komarev** [comment]
I've got same issue.

**Comment by faustbrian** [comment]
I am probably missing what the point of registering the provider via AppServiceProvider is. I can't come up with any real life use case for that so please give me an extensive example.

**Comment by faustbrian** [comment]
You should also try if the same happens with `Laravel\Socialite\SocialiteServiceProvider` as we only extend this provider from Socialite so the Provider is pretty much the original one.
