### ISSUE TITLE
FatalErrorException in AbstractProvider.php line 35: For AZURE

### ISSUE THREAD

**Issue by ekhlascyblance** [SocialiteProviders/Manager#99]
Call to undefined method SocialiteProviders\Azure\Provider::getAccessTokenResponse()

no getAccessTokenResponse function found
please give the proper solution.

**Comment by faustbrian** [comment]
`please give the proper solution.` This is an open-source project so feel free to send a PR since you are experiencing the issue and should be able to figure it out as you are a developer. Thanks.

**Comment by ekhlascyblance** [comment]
/vendor/socialiteproviders/manager/src/OAuth2/AbstractProvider.php:
   35:         $response = $this->getAccessTokenResponse($this->getCode());
Where **getAccessTokenResponse($this->getCode())** function used for getting some response(I dont know what type of response) 
I mean I am not able to find any function named **"getAccessTokenResponse" SocialiteProviders/Manager** But the method is called in **/vendor/socialiteproviders/manager/src/OAuth2/AbstractProvider.php:
   35:         $response = $this->getAccessTokenResponse($this->getCode());**
so what is the use of the function and what is it have in it.

**Comment by faustbrian** [comment]
I don't use Azure and thus have no account with them so someone that has an account will need to take a look at that. You seem to have an account and I am sure you are more then capable to fix the issue if you try and take a look at it.

**Comment by bkuhl** [comment]
I'm seeing the same issue with the Discord implementation.  It's an issue that exists with anything that utilizes the `AbstractProvider` as that base abstract class doesn't have access to this method at all anymore.
